apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config 
  namespace: zomato-ns
data:
  REACT_APP_API_URL: http://localhost:8000
  HOST: "0.0.0.0"
  MONGO_INITDB_DATABASE: zomato_clone
  MONGO_URL: mongodb://mongo-service:27017/zomato_clone
  API_GATEWAY_URL: http://api-gateway-service:8000